application: gitasoftweb
version: 1
runtime: python
api_version: 1

#builtins:
#- remote_api: on

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /static
  static_dir: static/
  expiration: '0'

- url: /.*
  script: django_bootstrap.py
