application: gitasoftweb
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:

- url: /static
  static_dir: static/
  expiration: '0'

- url: /.*
  script: django_bootstrap.py
